### ISSUE TITLE
404 error at demo site

### ISSUE THREAD

**Issue by zenflow** [illinois/next-page-transitions#10]
https://next-page-transitions.now.sh/ seems to be down

**Comment by nwalters512** [comment]
Oops, looks like I might have deleted the deployment while cleaning out some old ones. Let me get this back online!

**Comment by nwalters512** [comment]
This should be fixed now! Thanks for reporting this 🙂

**Comment by rahulbhanushali** [comment]
Demo seems to be broken again.
