### ISSUE TITLE
Maintaining / transitioning between same elements on existing and destination pages

### ISSUE THREAD

**Issue by Irrelon** [illinois/next-page-transitions#12]
Hey there.

I'm fairly new to the _app.js changes in next.js and using this component is working for me to transition if we only do opacity from the existing to the new page as per your example.

What about if we want to have an element that exists on both the existing and destination pages transition?

A good example is to watch the https://page-transitions.com/ example with the girl's avatar image and the background image in the header.

The image transitions between the existing css and target css nicely.

Could you point me in the right direction to achieve this?

Many thanks, and apologies if this is a newbie / obvious thing that I've just not figured out!

**Comment by nwalters512** [comment]
Sure, would be happy to point you in the right direction! So first off, there's a Next.js version of that same demo you linked to: https://page-transitions.now.sh/. Source is at https://github.com/xavczen/nextjs-page-transitions. If you look at that, they have an `_app.js` that renders an `AppNavigation` component no matter what the current route is: https://github.com/xavczen/nextjs-page-transitions/blob/master/pages/_app.js#L53. They also pass a `pathname` prop to that component so it knows which path to transition to/from. Then later in `_app.js`, they render the actual page, which changes as the route changes: https://github.com/xavczen/nextjs-page-transitions/blob/master/pages/_app.js#L69

So this package doesn't do quite what you're looking for; you'll need to build some more components and maybe restructure your app for such shared element transitions. However, if the elements that are changing are only in some shared persistent header, it would be totally feasible to mix that with this package: you manually transition the header and let this package transition the body. If the shared elements are in the body, things become a bit trickier, and I don't have any particularly good advice for you 😛 

Let me know if that makes sense!

**Comment by Irrelon** [comment]
Hey thanks so much for the detailed response. You pointed me in the right direction and I now have per-element transitions working without changing anything structure-wise :) The system doesn't require that the elements exist on the same page / component either :) I'll put together demo page in a couple of days.

**Comment by nwalters512** [comment]
Glad to hear that helped! I'll close this issue now. Would love to see the demo when it's done 🎉
