### ISSUE TITLE
Loader didn't appear on first route change

### ISSUE THREAD

**Issue by renodesper** [illinois/next-page-transitions#14]
Hi, when I first load the page and move to another route, the loader only show a blank screen. But when I move again to another page (or back to the previous page), the loader appear like how it should be.

- Is it use code splitting? 
- Is there anything that I can do to fix that?

**Comment by nwalters512** [comment]
Without more information, it'll be impossible for me to look into this. It might be related to #19. I'm closing this for now - if you have more info to share, I'd be happy to reopen and dig into this!
