### ISSUE TITLE
Page transition rerendering component when _app state changes

### ISSUE THREAD

**Issue by petrovichm** [illinois/next-page-transitions#16]
Hello,

I am using this component for transitioning routed component in nextjs.

Problem comes when you change something in state in `_app.js` file, which manages applications wrapper, render will fire, which is expected behavior. But along with it, children of `<PageTransition>` component will re-render. Now, this will unmount and mount everything inside.

There should be some kind of custom `shouldComponentUpdate` implementation that if children don't change, you don't re-render them. Since the point of transition is to animate only if children of `<PageTransition>` change.

I suppose this can be solved if you replace React.Component with React.PureComponent, i guess that shallow comparison of React will do the job.

Thanks,
 Mario

**Comment by nwalters512** [comment]
Did you check out the "Handling Context/Store changes that update props on the Component" section on the Readme?

**Comment by nwalters512** [comment]
No worries, glad I could be of some help!

**Comment by davidqqq** [comment]
> Did you check out the "Handling Context/Store changes that update props on the Component" section on the Readme?

Sorry but I could not find such section in Readme.

**Comment by borispoehland** [comment]
+1, can't find this in the readme
