### ISSUE TITLE
Figure out how to handle scrolling gracefully

### ISSUE THREAD

**Issue by nwalters512** [illinois/next-page-transitions#2]
By default, Next.js scrolls to the top of a page when a `Link` is clicked: https://github.com/zeit/next.js/blob/13cf9429f766c0542106504efc8f195ed87b8671/lib/link.js#L79. However, this is undesirable when using transitions, because the page will jump to the top before the transition has completed (or maybe before it's even started).

It doesn't look like Next supports disabling scrolling on all `Link` components (just with a one-off `scroll={false}` prop). Options include convincing Next to allow disabling this behavior at the app level, or possibly monkey-patching `window.scrollTo` to disable Next's scrolling during a transition.

**Comment by dextermb** [comment]
Surely this would help:

https://github.com/zeit/next.js/blob/canary/readme.md#disabling-the-scroll-changes-to-top-on-page

**Comment by nwalters512** [comment]
Resolved for now with ba40f13
