### ISSUE TITLE
Is monkeyPatchScrolling necessary?

### ISSUE THREAD

**Issue by 7ma7X** [illinois/next-page-transitions#24]
The aim of `monkeyPatchScrolling` seems to be preventing window from scrolling to the top of the page before you move to another page. However this effect can be turned off by setting `scroll` prop false.

```jsx
<Link scroll={false} href="/?counter=10"><a>Disables scrolling</a></Link>
```

https://github.com/zeit/next.js#disabling-the-scroll-changes-to-top-on-page

Why not recommend to use this default property? Are there any reasons to keep on `monkeyPatchScrolling`?

**Comment by nwalters512** [comment]
For a large app, adding that to all links may be time-consuming, and it would be easy to forget it and inadvertently end up with a bad UX. I'd welcome a PR with an update to the docs suggesting the `scroll` prop as an alternative though!
