### ISSUE TITLE
Is exist a "loading-indicator-exit" function?

### ISSUE THREAD

**Issue by Hocoh** [illinois/next-page-transitions#25]
I'm trying to handle my loading-component exit, but I fail, I'm wondering if there is this kin of functionality in nextjs?

Any hint would be great,
thanks

**Comment by nwalters512** [comment]
Are you asking about the classes that are applied to the loading indicator?

**Comment by nwalters512** [comment]
Closing as stale. If this is still a problem for you, let me know.
