### ISSUE TITLE
Can this be used outside from the <App> component?

### ISSUE THREAD

**Issue by billcastillo** [illinois/next-page-transitions#26]
Currently there is no example on how to use it outside the <App> component.
My intent is to not have a transition effect for the repeating component like the navigation header

Or am I wrong? does the whole page re-renders when switching pages?

**Comment by nwalters512** [comment]
This is just a component, there's nothing special about it. It can be used anywhere in your component hierarchy. For an example of a nav header that doesn't change on page transitions, see https://github.com/illinois/queue/blob/master/src/components/AppContainer.js
