### ISSUE TITLE
NextJS HMR functionality breaks

### ISSUE THREAD

**Issue by Schmerb** [illinois/next-page-transitions#27]
When using PageTransition HOC inside of `_app.js`, HMR functionality stops working.

Changes to:
 `_app.js` --> triggers `[HMR] bundle rebuilding` and the DOM **IS updated**

any other file scoped below `_app.js` -->  triggers `[HMR] bundle rebuilding`  but  DOM is **NOT updated**

Any suggestions on a possible solution / workaround?

**Comment by nwalters512** [comment]
I actually didn't see this issue and discovered this independently today - I'd been wondering why HMR wasn't working in my app, but when I added this to a new app and saw HMR break, I was finally able to find the culprit. I'm working on a fix for this for the v1.0.0 release, which I hope to ship later today. Thanks for reporting this!

**Comment by Schmerb** [comment]
Oh excellent! No worries, I appreciate the response. I was just going to implement this last, but looking forward to the fix
