### ISSUE TITLE
Provide transition state through the new Reat Context API

### ISSUE THREAD

**Issue by Pushplaybang** [illinois/next-page-transitions#28]
The class changes are great, but in some instances, you may want a more intricate transition and it would be great ot respond to the page transition states from specific components in the page, especially when working with css modules for instance.

While its totally possible to solve my use case using CSS, I think it would be beneficial to have the option of accessing this state, and being able to use JS animations if and when we would like to.

**Comment by nwalters512** [comment]
Agreed that it would be nice to be able to have more intricate transitions. Can you provide an outline of the API you're picturing?

**Comment by nwalters512** [comment]
Closing due to lack of response. Would be happy to reopen in the future if you have more ideas to share!
