### ISSUE TITLE
MonkeyPatchScrolling not auto scrolling on Mobile after transition

### ISSUE THREAD

**Issue by sendy34** [illinois/next-page-transitions#33]
On Desktop, enabling monkeypatchscrolling works fine:
1) Window don't scroll while exit transitions of current page
2) When Exit is done, window is scrolled to Top
3) Then New page transitions comes

But on mobile, the 2nd Step is not working.

Thanks!

**Comment by nwalters512** [comment]
What browser is this on? Can you provide a small self-contained example that demonstrates this? Something hosted on Now would be awesome.

**Comment by sendy34** [comment]
@nwalters512 
Actually it was an issue when a single page like index.js renders multiple pages based on Slug.
Since that Index Component updates on URL Changes and gets new props.

I will try to upload something on Zeit.

**Comment by va-studio** [comment]
@nwalters512 we're currently developing a website and we're having the same issue. Can you explain me exactly the solution? Thanks
