### ISSUE TITLE
Transitions with JavaScript Hooks

### ISSUE THREAD

**Issue by IGassmann** [illinois/next-page-transitions#40]
Is there any plan to support JavaScript hooks for page transitions like close to what [Nuxt.js does](https://nuxtjs.org/api/pages-transition/)?

`react-transition-group` already has somes JS hooks with their `<Transition>` component. The idea is to be able to use JS animation libraries such as GSAP, and ideally even have a `done` callback as a parameter to be used on the completion of an animation.

Otherwise, is it possible already to use `react-transition-group` with Next.js to achieve those type of page transitions?

**Comment by nwalters512** [comment]
I don't have any plans to implement this at the moment, but I would be open to a PR implementing this! Could you elaborate on the kind of API you have in mind?

Also, to clarify: you're referring to hooks in the sense of a callback and not React Hooks, right?

**Comment by IGassmann** [comment]
Yes, that would be in the sense of callbacks and not React Hooks.

The API I had in mind is the one currently used by Nuxt.js:
- `beforeEnter(element)`
- `enter(element, done)`
- `afterEnter(element)`
- `enterCancelled(element)`
- `beforeLeave(element)`
- `leave(element, done)`
- `afterLeave(element)`
- `leaveCancelled(element)`

**Comment by bravokiloecho** [comment]
@IGassmann, I raised a feature request on the Next.js repo for this to be handled within the framework. Would be good to get your input there if the idea appeals: https://github.com/vercel/next.js/issues/13149
