### ISSUE TITLE
Slide effect

### ISSUE THREAD

**Issue by lishine** [illinois/next-page-transitions#43]
Can I do the slide effect like with the mobile apps?
For this effect the next page must be mounted before the previous page unmounted, as I understand it

**Comment by nwalters512** [comment]
Can you clarify what you mean by "side effects"? A concrete example might be helpful.

**Comment by lishine** [comment]
You know like with any mobile app.
You swipe, and while still holding your finger, the new tab slides into view, while the previous slides out of view.
But I figure it out that with Next you have to fully unmount page first. 
It can be done in SAPP

**Comment by reck1ess** [comment]
It's impossible to implement 100% native-like page transition based on this library.

If you want native-like transition (e.g. iOS edge swipe), You should make your own page stack implementation, such as iOS's UINavigationController.

Here is a link for reference. 
[LINE Manga: smooth transition with Page Stack](http://tech.colla.me/en/show/line_manga_smooth_transition_with_page_stack)

**Comment by nwalters512** [comment]
Closing since it looks like a solution was found 👍
